version: '3.3'

services:
  tempomail:
    image: tempomail
    build: .
    volumes:
      - ./src/db.sqlite3:/app/src/db.sqlite3
    ports:
     - 8000:8000
    environment:
      - DEBUG=False
      - REDIS_HOST=redis
      # lifetimes in seconds
      - USER_LIFETIME=3600 
      - ADDRESS_LIFETIME=60
    depends_on:
       - redis
       - celery

  celery:
    image: tempomail
    command: celery -A TempoMail worker -l info
    volumes:
      - ./src/db.sqlite3:/app/src/db.sqlite3
    environment:
      - DEBUG=False
      - REDIS_HOST=redis
      # lifetimes in seconds
      - USER_LIFETIME=3600 
      - ADDRESS_LIFETIME=60
    depends_on:
       - redis
  
  redis:
    image: redis:alpine
      